# Default values for nodejs , fastapi, mariadb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  frontend:
    repository: hy30k/k8s-frontend:fpj
    tag: "v1"  # 기본 태그 설정

  mariadb:
    repository: mariadb
    tag: "10.6.19-focal"

  admin:
    repository: hy30k/k8s-admin:fpj
    tag: "v1"

  visitor:
    repository: hy30k/k8s-visitor:fpj
    tag: "v1"

service:
  frontend:
    port: 3000

  mariadb:
    port: 3306

  admin:
    port: 8000

  visitor:
    port: 8050
