# Default values for nodejs , fastapi, mariadb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  frontend:
    repository: hy30k/prj-frontend
    tag: v27

  mariadb:
    repository: mariadb
    tag: "10.6.19-focal"

  admin:
    repository: hy30k/prj-admin
    tag: v27

  visitor:
    repository: hy30k/prj-visitor
    tag: v27

service:
  frontend:
    port: 3000

  mariadb:
    port: 3306

  admin:
    port: 8000

  visitor:
    port: 8050
